some cleaning and docu update

diff --git a/start_container b/start_container
--- a/start_container
+++ b/start_container
@@ -5,9 +5,17 @@ fails=0
 
 # Check arguments.
 if [ ${#} -eq 0 ] ; then 
-    echo "Usage: ${0} SUPPORTCONFIG..." >&2
+    echo "Usage: ${0} [--fg] SUPPORTCONFIG..." >&2
     exit 1
 fi 
+
+# Skip foreground option.
+if [ "${1}" == '--fg' ] ; then
+    shift
+    foreground=1
+else
+    foreground=0
+fi
 
 # Walk trough config file.
 while read def ; do
@@ -35,12 +43,17 @@ while read def ; do
     id="${def#*:}"
 
     # Check if container is already running.
-    if [ -z $(docker ps -f "name=${name}" --format '{{.Names}}') ] ; then 
-        if docker run -d -i --name="${name}" --rm -e "MACHINE_ID=${id}" -e "SUPPORTCONFIG=${supportconfig_container}" -v ./sc:/sc -v "${supportconfig}:${supportconfig_container}" --network=wanda_default -t sc_runner /sc/startup > /dev/null ; then
-            echo "Container \"${name}\" started for supportconfig \"${supportconfig}\"."
-        else
-            echo "Starting container \"${name}\" for supportconfig \"${supportconfig}\" failed!" >&2
-            (( fails++ ))
+    if [ -z $(docker ps -f "name=${name}" --format '{{.Names}}') ] ; then
+        if [ ${foreground} -eq 1 ] ; then
+            echo "Starting container \"${name}\" for supportconfig \"${supportconfig}\" in the foreground:"
+            docker run --name="${name}" --rm -e "MACHINE_ID=${id}" -e "SUPPORTCONFIG=${supportconfig_container}" -v ./sc:/sc -v "${supportconfig}:${supportconfig_container}" --network=wanda_default -t sc_runner /sc/startup
+        else 
+            if docker run -d -i --name="${name}" --rm -e "MACHINE_ID=${id}" -e "SUPPORTCONFIG=${supportconfig_container}" -v ./sc:/sc -v "${supportconfig}:${supportconfig_container}" --network=wanda_default -t sc_runner /sc/startup > /dev/null ; then
+                echo "Container \"${name}\" started for supportconfig \"${supportconfig}\"."
+            else
+                echo "Starting container \"${name}\" for supportconfig \"${supportconfig}\" failed!" >&2
+                (( fails++ ))
+            fi
         fi
     else
         echo "Container \"${name}\" is already running! Stop all suportconfig containers with \"stop_container\"!" >&2 
