start manifest integration

diff --git a/sc/process_supportfiles b/sc/process_supportfiles
--- a/sc/process_supportfiles
+++ b/sc/process_supportfiles
@@ -37,12 +37,11 @@ else
     echo "${SUPPORTCONFIG} is neither file nor directory." >&2
     exit 1
 fi
-./split-supportconfig "${supportconfig_dir}/etc.txt" "${supportconfig_dir}/sysconfig.txt" "${supportconfig_dir}/basic-environment.txt" "${supportconfig_dir}/ha.txt" "${supportconfig_dir}/plugin-ha_sap.txt" "${supportconfig_dir}/fs-diskio.txt" || exit 1   # hard exit to let host creation fail 
+./split-supportconfig "${supportconfig_dir}/network.txt" "${supportconfig_dir}/etc.txt" "${supportconfig_dir}/sysconfig.txt" "${supportconfig_dir}/basic-environment.txt" "${supportconfig_dir}/ha.txt" "${supportconfig_dir}/plugin-ha_sap.txt" "${supportconfig_dir}/fs-diskio.txt" || exit 1   # hard exit to let host creation fail 
 
 # Copy files from supportconfig into rootfs.
 mkdir /etc/corosync/
-
-rm -f /etc/corosync/corosync.conf /etc/sysconfig/sbd /etc/os-release /etc/fstab
+rm -f /etc/corosync/corosync.conf /etc/sysconfig/sbd /etc/os-release /etc/fstab /etc/hosts
 rm -fr /var/lib/pacemaker /usr/sap
 cp -b /rootfs/etc/corosync/corosync.conf /etc/corosync/ ; add_temp_manifest 'corosync.conf'
 cp -b /rootfs/etc/sysconfig/sbd /etc/sysconfig/ ; add_temp_manifest 'sysconfig_sbd'
@@ -50,6 +49,7 @@ cp -b /rootfs/etc/os-release /etc/ ; add_temp_manifest 'os-release'
 cp -r /rootfs/var/lib/pacemaker /var/lib/ ; add_temp_manifest 'pacemaker_files'
 cp -r /rootfs/usr/sap /usr/ ; add_temp_manifest 'usr_sap'
 cp -r /rootfs/etc/fstab /etc/ ; add_temp_manifest 'fstab'
+cp -r /rootfs/etc/hosts /etc/ ; add_temp_manifest 'hosts'
 
 # Extract saptune JSON output.
 rm -f /tmp/saptune_status.json /tmp/saptune_note_verify.json /tmp/saptune_note_list.json /tmp/saptune_check.json
